import {Images} from '../../components';
export const stakingArray = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    name: 'LEGEND',
    price: '1000',
    tokenName: 'Sizzle',
    image: Images.leotoken,
    apy: '35% APY',
    arcadia: 'Arcadia: Unlimited Turns on Daily Challenge',
    bizpad: 'Access to Bizpad',
    Launchpad: 'Level 3 on Sizzle Launchpad',
    Bluemoon: 'Additional Bluemoon Perks',
    Rewards: '1 Feature on Legion Rewards',
    vip: 'VIP Member Pass in events/retreats/meetups (Direct access to core team)',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad33abb28ba',
    name: 'DIAMOND',
    price: '1000',
    tokenName: 'Sizzle',
    image: Images.avalanche,
    apy: '35% APY',
    arcadia: 'Arcadia: Unlimited Turns on Daily Challenge',
    bizpad: 'Access to Bizpad',
    Launchpad: 'Level 3 on Sizzle Launchpad',
    Bluemoon: 'Additional Bluemoon Perks',
    Rewards: '1 Feature on Legion Rewards',
    vip: 'VIP Member Pass in events/retreats/meetups (Direct access to core team)',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad66abb28ba',
    name: 'PLATINUM',
    price: '1000',
    tokenName: 'Sizzle',
    image: Images.ethereum,
    apy: '35% APY',
    arcadia: 'Arcadia: Unlimited Turns on Daily Challenge',
    bizpad: 'Access to Bizpad',
    Launchpad: 'Level 2 on Sizzle Launchpad',
    Bluemoon: 'Additional Bluemoon Perks',
    Rewards: '1 Feature on Legion Rewards',
    vip: 'VIP Member Pass in events/retreats/meetups (Direct access to core team)',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb2554',
    name: 'GOLD',
    price: '1000',
    tokenName: 'Sizzle',
    image: Images.matic,
    apy: '35% APY',
    arcadia: 'Arcadia: Unlimited Turns on Daily Challenge',
    bizpad: 'Access to Bizpad',
    Launchpad: 'Level 1 on Sizzle Launchpad',
    Bluemoon: 'Additional Bluemoon Perks',
    Rewards: '1 Feature on Legion Rewards',
    vip: 'VIP Member Pass in events/retreats/meetups (Direct access to core team)',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3a5753abb28ba',
    name: 'SILVER',
    price: '1000',
    tokenName: 'Sizzle',
    image: Images.matic,
    apy: '35% APY',
    arcadia: 'Arcadia: Unlimited Turns on Daily Challenge',
    bizpad: 'Access to Bizpad',
    Launchpad: 'Level 3 on Sizzle Launchpad',
    Bluemoon: 'Additional Bluemoon Perks',
    Rewards: '1 Feature on Legion Rewards',
    vip: 'VIP Member Pass in events/retreats/meetups (Direct access to core team)',
  },
];

export default {
  stakingArray,
};
