const Images = {
  splash: require('../assets/Images/splash.png'),
  profile: require('../assets/Images/profile.png'),
  Radix: require('../assets/Images/Radix.webp'),
  Playstoreicon: require('../assets/Images/Playstoreicon.png'),
  Instagram: require('../assets/Images/Instagram.png'),
  twitter: require('../assets/Images/twitter.png'),
  linkdin: require('../assets/Images/linkdin.png'),
  appstore: require('../assets/Images/appstore.png'),
  avalanche: require('../assets/Images/avalanche.webp'),
  leotoken: require('../assets/Images/leo-token.webp'),
  bluemoon: require('../assets/Images/bluemoon.png'),
  playToEarn: require('../assets/Images/playToEarn.jpeg'),
  ethereum: require('../assets/Images/ethereum.webp'),
  matic: require('../assets/Images/matic.webp'),
  profileImage: require('../assets/Images/profileImage.png'),
  createWalletImage: require('../assets/Images/createWalletImage.png'),
  bitcoinCourse: require('../assets/Images/courses/bitcoin.jpg'),
  ethereumCourse: require('../assets/Images/courses/ethereum.jpg'),
  binanceCoinCourse: require('../assets/Images/courses/binance-coin.jpg'),
  otherCryptoCourse: require('../assets/Images/courses/other.jpg'),
  cryptoVidSmThumb1: require('../assets/Images/courses/sm-thumb1-bitcoin.jpg'),
  cryptoVidSmThumb2: require('../assets/Images/courses/sm-thumb2-ethereum.jpg'),
  cryptoVidSmThumb3: require('../assets/Images/courses/sm-thumb3-ff.jpg'),
  cryptoVidSmThumb4: require('../assets/Images/courses/sm-thum4-mining.jpg'),
  cryptoVidSmThumb5: require('../assets/Images/courses/sm-thumb5-multi.jpg'),
  cryptoVidSmThumb6: require('../assets/Images/courses/sm-thum6-trading.jpg'),
  isCheckedCustom: require('../assets/checkbox/custom_checked.png'),
  isUnCheckedCustom: require('../assets/checkbox/custom_unchecked.png'),
  littleNightmare: require('../assets/Images/games/lnm2.jpg'),
  genshin: require('../assets/Images/games/gi.jpg'),
  pokemon: require('../assets/Images/games/pu.jpg'),
  bnblogo:require('../assets/Images/bnblogo.png'),
  tokenplaceholder:require('../assets/Images/tokenplaceholder.png'),
  cardicon:require('../assets/Images/cardicon.png'),
  settingicon:require('../assets/Images/settingicon.png'),
  arrowdown:require('../assets/Images/FAQ/arrowdown.png'),
  arrowup:require('../assets/Images/FAQ/arrowup.png'),
  Wesite:require('../assets/Images/Community/Wesite.png'),

  discordchannal:require('../assets/Images/Community/discordchannal.png'),
  telegram:require('../assets/Images/Community/telegram.png'),
  Instagram:require('../assets/Images/Community/Instagram.png'),
  linkdin:require('../assets/Images/Community/linkdin.png'),
  twitter:require('../assets/Images/Community/twitter.png'),
  Reddit:require('../assets/Images/Community/Reddit.png'),
  Facebook:require('../assets/Images/Community/Facebook.png'),
  Medium:require('../assets/Images/Community/Medium.png'),
  Bscscan:require('../assets/Images/Community/Bscscan.png'),
  Youtube:require('../assets/Images/Community/Youtube.png'),
  nextGray:require('../assets/Images/Community/nextGray.png'),



  
};
export default Images;
